/**
 * Set de iconos único de la app: Phosphor Icons (peso regular, terminales
 * redondeadas). Se exporta con nombres semánticos estables para que ningún
 * componente importe dos sets distintos.
 */
export type { Icon as AppIcon } from "@phosphor-icons/react";

export {
  Check,
  Checks as CheckCheck,
  Clock,
  FileText,
  Image as ImageIcon,
  ArrowBendUpLeft as CornerUpLeft,
  ArrowBendUpRight as Forward,
  WarningCircle as AlertCircle,
  Pause,
  Play,
  Camera,
  Microphone as Mic,
  Paperclip,
  PaperPlaneRight as Send,
  Trash as Trash2,
  X,
  Key as KeyRound,
  Laptop,
  SignOut as LogOut,
  DeviceMobile as Smartphone,
  BellSlash as BellOff,
  Bell,
  Plus,
  ChatTeardropDots as MessageSquarePlus,
  MagnifyingGlass as Search,
  UsersThree as Users,
  User,
  ChatCircle as MessageCircle,
  NotePencil as NotebookPen,
  ShieldCheck,
  PencilSimple as Pencil,
  Phone,
  UserPlus,
  Envelope as Mail,
  Archive,
  ArrowCounterClockwise as ArchiveRestore,
  ListChecks,
  CaretRight as ChevronRight,
  CaretLeft as ChevronLeft,
  Moon,
  Sun,
  At as AtSign,
  Lock,
  Smiley,
  Timer,
  PushPin as Pin,
  PushPinSlash as PinOff,
  DotsThree as MoreHorizontal,
  Bluetooth,
  BluetoothConnected,
  BluetoothSlash,
  BatteryHigh,
  CellSignalFull as SignalFull,
  SpinnerGap as Spinner,
  HardHat as Helmet,
  MapPin,
  NavigationArrow,
  TextT,
  Eye,
  CaretUp as ChevronUp,
  Car,
  Siren as Ambulance,
  WifiHigh as Wifi,
  WifiSlash as WifiOff,
  Broadcast,
} from "@phosphor-icons/react";
