/**
 * Datos simulados de la fase 1. Se reemplazan por el backend real sin cambiar los tipos.
 */
import statusSample from "@/assets/status-sample.jpg";
import type {
  Chat,
  ConnectedDevice,
  Contact,
  Message,
  Note,
  StatusUpdate,
  UserProfile,
} from "./types";

export const CURRENT_USER_ID = "user_me";

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

export const MOCK_CONTACTS: Contact[] = [
  {
    id: "contact_1",
    ownerId: CURRENT_USER_ID,
    displayName: "Camila Restrepo",
    phoneNumber: "+573001112233",
    avatarUrl: null,
    hasAppAccount: true,
    linkedUserId: "user_camila",
    source: "device",
    isInvited: false,
  },
  {
    id: "contact_2",
    ownerId: CURRENT_USER_ID,
    displayName: "Andrés Gómez",
    phoneNumber: "+573014445566",
    avatarUrl: null,
    hasAppAccount: true,
    linkedUserId: "user_andres",
    source: "device",
    isInvited: false,
  },
  {
    id: "contact_3",
    ownerId: CURRENT_USER_ID,
    displayName: "Valentina Ríos",
    phoneNumber: "+573027778899",
    avatarUrl: null,
    hasAppAccount: true,
    linkedUserId: "user_valentina",
    source: "device",
    isInvited: false,
  },
  {
    id: "contact_4",
    ownerId: CURRENT_USER_ID,
    displayName: "Mateo Herrera",
    phoneNumber: "+573039990011",
    avatarUrl: null,
    hasAppAccount: true,
    linkedUserId: "user_mateo",
    source: "manual",
    isInvited: false,
  },
  {
    id: "contact_5",
    ownerId: CURRENT_USER_ID,
    displayName: "Laura Peña",
    phoneNumber: "+573042223344",
    avatarUrl: null,
    hasAppAccount: false,
    linkedUserId: null,
    source: "device",
    isInvited: false,
  },
  {
    id: "contact_6",
    ownerId: CURRENT_USER_ID,
    displayName: "Sebastián Ortiz",
    phoneNumber: "+573055556677",
    avatarUrl: null,
    hasAppAccount: false,
    linkedUserId: null,
    source: "device",
    isInvited: false,
  },
  {
    id: "contact_7",
    ownerId: CURRENT_USER_ID,
    displayName: "Daniela Cortés",
    phoneNumber: "+573068889900",
    avatarUrl: null,
    hasAppAccount: false,
    linkedUserId: null,
    source: "device",
    isInvited: true,
  },
];

export const MOCK_PARTICIPANTS: Record<string, UserProfile> = Object.fromEntries(
  MOCK_CONTACTS.filter((c) => c.linkedUserId).map((c) => [
    c.linkedUserId as string,
    {
      id: c.linkedUserId as string,
      displayName: c.displayName,
      about: "Disponible",
      avatarUrl: null,
      phoneNumber: c.phoneNumber,
      phoneCountryCode: "CO",
      email: null,
      isPhoneVerified: true,
      isEmailVerified: false,
      lastSeenAt: minutesAgo(12),
      isOnline: c.id === "contact_1",
      createdAt: minutesAgo(60 * 24 * 200),
    } satisfies UserProfile,
  ]),
);

/** Estados/historias simulados de las últimas 24 h. */
export const MOCK_STATUSES: StatusUpdate[] = [
  {
    id: "status_1",
    authorId: "user_camila",
    kind: "media",
    body: "Vaciado de placa terminado en la torre 2",
    backgroundColor: null,
    mediaUrl: statusSample,
    audience: { mode: "all", contactIds: [] },
    createdAt: minutesAgo(95),
    expiresAt: new Date(Date.now() + (24 * 60 - 95) * 60_000).toISOString(),
    views: [],
  },
  {
    id: "status_2",
    authorId: "user_camila",
    kind: "text",
    body: "Mañana revisamos el hito 4 a primera hora ☀️",
    backgroundColor: "#5B4FE5",
    mediaUrl: null,
    audience: { mode: "all", contactIds: [] },
    createdAt: minutesAgo(40),
    expiresAt: new Date(Date.now() + (24 * 60 - 40) * 60_000).toISOString(),
    views: [],
  },
  {
    id: "status_3",
    authorId: "user_andres",
    kind: "text",
    body: "Interventoría en campo todo el día",
    backgroundColor: "#F5A623",
    mediaUrl: null,
    audience: { mode: "all", contactIds: [] },
    createdAt: minutesAgo(220),
    expiresAt: new Date(Date.now() + (24 * 60 - 220) * 60_000).toISOString(),
    views: [],
  },
  {
    id: "status_4",
    authorId: "user_valentina",
    kind: "media",
    body: "Avance de fachada",
    backgroundColor: null,
    mediaUrl: statusSample,
    audience: { mode: "all", contactIds: [] },
    createdAt: minutesAgo(600),
    expiresAt: new Date(Date.now() + (24 * 60 - 600) * 60_000).toISOString(),
    // Ya visto por el usuario actual: la burbuja muestra anillo gris.
    views: [{ viewerId: CURRENT_USER_ID, viewedAt: minutesAgo(500) }],
  },
];

const RAW_CHATS: Array<Omit<Chat, "disappearingTtlSeconds">> = [
  {
    id: "chat_1",
    participantIds: [CURRENT_USER_ID, "user_camila"],
    title: "Camila Restrepo",
    avatarUrl: null,
    lastMessagePreview: "Nota de voz",
    lastMessageAt: minutesAgo(3),
    unreadCount: 2,
    isMuted: false,
    isPinned: false,
    pinnedAt: null,
    mutedUntil: null,
    archivedAt: null,
    activity: "typing",
    isGroup: false,
    adminIds: [],
  },
  {
    id: "chat_2",
    participantIds: [CURRENT_USER_ID, "user_andres"],
    title: "Andrés Gómez",
    avatarUrl: null,
    lastMessagePreview: "Te paso el archivo hoy mismo",
    lastMessageAt: minutesAgo(48),
    unreadCount: 0,
    isMuted: false,
    isPinned: false,
    pinnedAt: null,
    mutedUntil: null,
    archivedAt: null,
    activity: "idle",
    isGroup: false,
    adminIds: [],
  },
  {
    id: "chat_3",
    participantIds: [CURRENT_USER_ID, "user_valentina"],
    title: "Valentina Ríos",
    avatarUrl: null,
    lastMessagePreview: "Foto",
    lastMessageAt: minutesAgo(60 * 5),
    unreadCount: 1,
    isMuted: true,
    isPinned: false,
    pinnedAt: null,
    mutedUntil: null,
    archivedAt: null,
    activity: "idle",
    isGroup: false,
    adminIds: [],
  },
  {
    id: "chat_4",
    participantIds: [CURRENT_USER_ID, "user_mateo"],
    title: "Mateo Herrera",
    avatarUrl: null,
    lastMessagePreview: "Listo, nos vemos el viernes",
    lastMessageAt: minutesAgo(60 * 30),
    unreadCount: 0,
    isMuted: false,
    isPinned: false,
    pinnedAt: null,
    mutedUntil: null,
    archivedAt: null,
    activity: "idle",
    isGroup: false,
    adminIds: [],
  },
  {
    id: "chat_group_1",
    participantIds: [CURRENT_USER_ID, "user_camila", "user_andres", "user_valentina", "user_mateo"],
    title: "Mudanza de oficina",
    avatarUrl: null,
    lastMessagePreview: "Yo llevo las cajas grandes",
    lastMessageAt: minutesAgo(12),
    unreadCount: 3,
    isMuted: false,
    isPinned: false,
    pinnedAt: null,
    mutedUntil: null,
    archivedAt: null,
    activity: "idle",
    isGroup: true,
    adminIds: [CURRENT_USER_ID],
  },

];
/** Chats simulados con los campos derivados por defecto. */
export const MOCK_CHATS: Chat[] = RAW_CHATS.map((chat) => ({
  ...chat,
  disappearingTtlSeconds: null,
}));

const WAVEFORM = [0.2, 0.5, 0.8, 0.4, 0.9, 0.6, 0.3, 0.7, 0.5, 0.85, 0.4, 0.6, 0.25, 0.7, 0.45];

const RAW_MESSAGES: Array<Omit<Message, "reactions" | "disappearingTtlSeconds">> = [
  {
    id: "msg_1",
    chatId: "chat_1",
    senderId: "user_camila",
    kind: "text",
    body: "¡Hola! ¿Alcanzaste a revisar la propuesta?",
    attachment: null,
    status: "read",
    createdAt: minutesAgo(42),
    editedAt: null,
    deletedAt: null,
    replyToMessageId: null,
    forwardedFromChatId: null,
  },
  {
    id: "msg_2",
    chatId: "chat_1",
    senderId: CURRENT_USER_ID,
    kind: "text",
    body: "Sí, la vi anoche. Me gustó mucho la última parte.",
    attachment: null,
    status: "read",
    createdAt: minutesAgo(38),
    editedAt: null,
    deletedAt: null,
    replyToMessageId: "msg_1",
    forwardedFromChatId: null,
  },
  {
    id: "msg_3",
    chatId: "chat_1",
    senderId: CURRENT_USER_ID,
    kind: "document",
    body: "",
    attachment: {
      kind: "document",
      url: "#",
      fileName: "propuesta-final.pdf",
      fileSizeBytes: 428_000,
    },
    status: "delivered",
    createdAt: minutesAgo(30),
    editedAt: null,
    deletedAt: null,
    replyToMessageId: null,
    forwardedFromChatId: null,
  },
  {
    id: "msg_4",
    chatId: "chat_1",
    senderId: "user_camila",
    kind: "voice",
    body: "",
    attachment: { kind: "voice", url: "#", durationSeconds: 14, waveform: WAVEFORM },
    status: "read",
    createdAt: minutesAgo(3),
    editedAt: null,
    deletedAt: null,
    replyToMessageId: null,
    forwardedFromChatId: null,
  },
  {
    id: "msg_5",
    chatId: "chat_2",
    senderId: "user_andres",
    kind: "text",
    body: "Te paso el archivo hoy mismo",
    attachment: null,
    status: "read",
    createdAt: minutesAgo(48),
    editedAt: null,
    deletedAt: null,
    replyToMessageId: null,
    forwardedFromChatId: null,
  },
  {
    id: "msg_6",
    chatId: "chat_3",
    senderId: "user_valentina",
    kind: "image",
    body: "",
    attachment: { kind: "image", url: "#", fileName: "obra-avance.jpg" },
    status: "delivered",
    createdAt: minutesAgo(60 * 5),
    editedAt: null,
    deletedAt: null,
    replyToMessageId: null,
    forwardedFromChatId: null,
  },
  {
    id: "msg_7",
    chatId: "chat_4",
    senderId: CURRENT_USER_ID,
    kind: "text",
    body: "Listo, nos vemos el viernes",
    attachment: null,
    status: "read",
    createdAt: minutesAgo(60 * 30),
    editedAt: null,
    deletedAt: null,
    replyToMessageId: null,
    forwardedFromChatId: null,
  },
  {
    id: "msg_g1",
    chatId: "chat_group_1",
    senderId: "user_camila",
    kind: "text",
    body: "¿A qué hora llega el camión el sábado?",
    attachment: null,
    status: "read",
    createdAt: minutesAgo(40),
    editedAt: null,
    deletedAt: null,
    replyToMessageId: null,
    forwardedFromChatId: null,
  },
  {
    id: "msg_g2",
    chatId: "chat_group_1",
    senderId: CURRENT_USER_ID,
    kind: "text",
    body: "A las 8 en punto. Llevemos todo empacado antes.",
    attachment: null,
    status: "read",
    createdAt: minutesAgo(35),
    editedAt: null,
    deletedAt: null,
    replyToMessageId: "msg_g1",
    forwardedFromChatId: null,
  },
  {
    id: "msg_g3",
    chatId: "chat_group_1",
    senderId: "user_andres",
    kind: "text",
    body: "Yo llevo las cajas grandes",
    attachment: null,
    status: "delivered",
    createdAt: minutesAgo(12),
    editedAt: null,
    deletedAt: null,
    replyToMessageId: null,
    forwardedFromChatId: null,
  },
];
/** Mensajes simulados; las reacciones de ejemplo se agregan abajo. */
export const MOCK_MESSAGES: Message[] = RAW_MESSAGES.map((message) => ({
  ...message,
  reactions:
    message.id === "msg_2"
      ? [{ emoji: "\u2764\ufe0f", userId: "user_camila", createdAt: message.createdAt }]
      : message.id === "msg_g3"
        ? [
            { emoji: "\ud83d\udc4d", userId: CURRENT_USER_ID, createdAt: message.createdAt },
            { emoji: "\ud83d\udc4d", userId: "user_camila", createdAt: message.createdAt },
            { emoji: "\ud83d\ude4f", userId: "user_valentina", createdAt: message.createdAt },
          ]
        : [],
  disappearingTtlSeconds: null,
}));

const NOTE_WAVEFORM = [0.3, 0.7, 0.45, 0.9, 0.6, 0.35, 0.8, 0.5, 0.75, 0.4, 0.65, 0.55];

export const MOCK_NOTES: Note[] = [
  {
    id: "note_1",
    ownerId: CURRENT_USER_ID,
    kind: "text",
    title: "Ideas para la propuesta",
    body: "Empezar con el caso de la obra de Chapinero y cerrar con los números del trimestre.",
    attachment: null,
    reminderAt: null,
    createdAt: minutesAgo(90),
    updatedAt: minutesAgo(25),
    archivedAt: null,
    isTask: false,
    taskStatus: null,
    completedAt: null,
  },
  {
    id: "note_2",
    ownerId: CURRENT_USER_ID,
    kind: "voice",
    title: null,
    body: "",
    attachment: { kind: "voice", url: "#", durationSeconds: 21, waveform: NOTE_WAVEFORM },
    reminderAt: null,
    createdAt: minutesAgo(60 * 6),
    updatedAt: minutesAgo(60 * 6),
    archivedAt: null,
    isTask: false,
    taskStatus: null,
    completedAt: null,
  },
  {
    id: "note_3",
    ownerId: CURRENT_USER_ID,
    kind: "text",
    title: null,
    body: "Llamar a la administración del edificio por el permiso de la terraza.",
    attachment: null,
    reminderAt: new Date(Date.now() + 3 * 60 * 60_000).toISOString(),
    createdAt: minutesAgo(60 * 26),
    updatedAt: minutesAgo(60 * 26),
    archivedAt: null,
    isTask: true,
    taskStatus: "pending",
    completedAt: null,
  },
  {
    id: "note_5",
    ownerId: CURRENT_USER_ID,
    kind: "text",
    title: null,
    body: "Enviar el acta firmada al interventor.",
    attachment: null,
    reminderAt: null,
    createdAt: minutesAgo(60 * 30),
    updatedAt: minutesAgo(60 * 20),
    archivedAt: null,
    isTask: true,
    taskStatus: "done",
    completedAt: minutesAgo(60 * 20),
  },
  {
    id: "note_4",
    ownerId: CURRENT_USER_ID,
    kind: "text",
    title: "Lista del mercado",
    body: "Café, pan, arequipe y fruta para la semana.",
    attachment: null,
    reminderAt: null,
    createdAt: minutesAgo(60 * 24 * 5),
    updatedAt: minutesAgo(60 * 24 * 5),
    archivedAt: minutesAgo(60 * 24 * 2),
    isTask: false,
    taskStatus: null,
    completedAt: null,
  },
];

export const MOCK_DEVICES: ConnectedDevice[] = [
  {
    id: "device_1",
    deviceName: "iPhone 15 de Jheison",
    platform: "ios",
    lastActiveAt: minutesAgo(1),
    isCurrentDevice: true,
  },
  {
    id: "device_2",
    deviceName: "Galaxy S23",
    platform: "android",
    lastActiveAt: minutesAgo(180),
    isCurrentDevice: false,
  },
  {
    id: "device_3",
    deviceName: "Chrome en Windows",
    platform: "web",
    lastActiveAt: minutesAgo(1440),
    isCurrentDevice: false,
  },
];
